### ISSUE TITLE
OpenSelery vs LibreSelery

### ISSUE THREAD

**Issue by Ly0n** [protontypes/libreselery#138]
We got feedback from one of the most experienced persons in free software development on this project.
He suggested to rename the project to LibreSelery.
So why is LibreSelery a good option?

1. I like the Celery logo that's why LibreSalary is no option.  I also like the ambiguous name selery since people are confused when reading the name in the first place. I speak from intensive experience ;)
2. Libre describes more what we are doing than Open. Yes, we are very transparent and "Open" but one of the most important aspects that we have is the freedom that we give to a project. 
3. FreeSalary or FreeSelery would be interesting but it will confuse people since they will think they will get salary for doing nothing. 

What is your opinion?

**Comment by fdietze** [comment]
How about LibreCelery?

**Comment by Ly0n** [comment]
> How about LibreCelery?
Yes that would also be a very good option. The problem is the celery project that is quite large:
https://github.com/celery/celery

**Comment by Ly0n** [comment]
The project is renamed now.
