### ISSUE TITLE
Improve transaction plots

### ISSUE THREAD

**Issue by ZeipsCode** [protontypes/LibreSelery#82]

**Comment by Ly0n** [comment]
This also relates to: #63

**Comment by Ly0n** [comment]
@ZeipsCode @cornerman @kikass13 
The plot EUR per User is wrong. Cornerman got much more than plotted here:
![](https://raw.githubusercontent.com/wiki/protontypes/openselery/openselery/transactions_per_user.png)
Any suggestions on how to improve that.

**Comment by cornerman** [comment]
How do you map email adresses to usernames? I haved used two different email adresses. And only one of them maps to my github account.

**Comment by Ly0n** [comment]
Github can do that:
https://stackoverflow.com/questions/44888187/get-github-username-through-primary-email
But you might create to many API calls.
